services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./ssl:/ssl

  backend:
    container_name: backend
    restart: unless-stopped
    build: ./backend
    environment:
      - PYTHONUNBUFFERED=1
      - UV_LINK_MODE=copy
      - TF_MODEL_PATH=${TF_MODEL_PATH}
    volumes:
      - ./backend:/app
      - ./backend/tf_models/model.keras:${TF_MODEL_PATH}

  frontend:
    container_name: frontend
    restart: unless-stopped
    build: ./frontend
    volumes:
      - ./frontend/app:/app
